### ISSUE TITLE
Improvement: Onboarding on re-signin only once per device

### ISSUE THREAD

**Issue by workerbee22** [suesitran/my_wallet#37]
When I sign out and then re-sign in, I'd prefer not to have the onboarding window show again that 'finds' my home again and asks me to press a button to get into the app. Expected behaviour is re-sign in takes me straight into the app. So onboarding experience should only run once per device.

**Comment by suesitran** [comment]
The app is designed for multiple user login, therefore the flow is to always show Welcome home/create your home screen after user login, regardless if the same user has logged-in in the device before.
