### ISSUE TITLE
Improvement: Fail gracefully when no internet connection

### ISSUE THREAD

**Issue by workerbee22** [suesitran/my_wallet#38]
Whilst logged in and using the app, if internet connectivity is removed, then the app should fail gracefully. To reproduce:
1. Signed into the app.
2. Put phone into Airplane mode (no internet connection)
3. Sign out (signs out with no errors so good)
4. Attempt to Sign back in, get error shown below

Expected behaviour is a friendlier error message eg. 'Login failed. You seem to have no internet connection right now, try again later.'

![image](https://user-images.githubusercontent.com/5154664/55659037-8e051500-584b-11e9-8013-6dd48c306c4b.png)

**Comment by suesitran** [comment]
Done after login UI update
