### ISSUE TITLE
Cannot run project after clonning

### ISSUE THREAD

**Issue by patricknasc** [suesitran/my_wallet#54]
I just cloned the repository and after getting the dependencies, when I try to run the project Im getting the following error: 

Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  C:\Users\Me\AndroidStudioProjects\my_wallet\lib\ui\splash\data\splash_repository.dart
...refers, in an import, to the following library:
  C:\Users\Me\AndroidStudioProjects\my_wallet\lib\firebase_config.dart
Unfortunately, that library does not appear to exist on your file system.

**Comment by suesitran** [comment]
That file is our private key and is meant to be share with collaborators only. If you wanna build the project, you need to create your own firebase project, get all the keys and update that file yourself.

**Comment by ketanchoyal** [comment]
can you give a sample of that file so that we can know the structure of firebase_config.dart file
